manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: xuke-zmk
      url-base: https://github.com/xuke-zmk

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: zmk_encoder
      remote: xuke-zmk
      revision: main
      path: modules/zmk_encoder
  self:
    path: config